// Mocks generated by Mockito 5.0.8 from annotations
// in ditonton/test/presentation/pages/series/episode_series_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:ditonton/common/state_enum.dart' as _i5;
import 'package:ditonton/domain/entities/episode_enitity.dart' as _i3;
import 'package:ditonton/domain/usecases/series/get_series_episode.dart' as _i2;
import 'package:ditonton/presentation/provider/series/series_episode_notifier.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeGetSeriesEpisode extends _i1.Fake implements _i2.GetSeriesEpisode {}

class _FakeEpisodeEntity extends _i1.Fake implements _i3.EpisodeEntity {}

/// A class which mocks [SeriesEpisodeNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockSeriesEpisodeNotifier extends _i1.Mock
    implements _i4.SeriesEpisodeNotifier {
  MockSeriesEpisodeNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetSeriesEpisode get getSeriesEpisode =>
      (super.noSuchMethod(Invocation.getter(#getSeriesEpisode),
          returnValue: _FakeGetSeriesEpisode()) as _i2.GetSeriesEpisode);
  @override
  _i5.RequestState get state => (super.noSuchMethod(Invocation.getter(#state),
      returnValue: _i5.RequestState.Empty) as _i5.RequestState);
  @override
  _i3.EpisodeEntity get series =>
      (super.noSuchMethod(Invocation.getter(#series),
          returnValue: _FakeEpisodeEntity()) as _i3.EpisodeEntity);
  @override
  String get message =>
      (super.noSuchMethod(Invocation.getter(#message), returnValue: '')
          as String);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i6.Future<void> fetchSeriesEpisode(int? id, int? season) =>
      (super.noSuchMethod(Invocation.method(#fetchSeriesEpisode, [id, season]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i6.Future<void>);
  @override
  void addListener(_i7.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i7.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}
